### ISSUE TITLE
Add units into the name of every numerical column in output files

### ISSUE THREAD

**Issue by lloyd-rmi** [msmasnadi/OPGEEv4#7]
It is difficult to always track what units the output data is in. Having them explicitly added into the name of each column would make it simple for us to always know what numbers we are dealing with.

**Comment by wennanlong** [comment]
Hi lloyd-rmi, Thank you for the feedback. I’ve added the units to all the output file names for clarity. The carbon intensity is now labeled in g/MJ, emissions in tonnes/day, energy in MMBtu/day, and gases in tonnes/day. The streams file includes units within the file itself.

**Comment by rjplevin** [comment]
Two issues with this approach: 
1. It's not guaranteed that all items in a file have the same units. Naming the file this way suggests otherwise. Adding units to columns, or perhaps generating an additional file with data -> unit mappings, would be more robust.
2. Hard-coding the units creates a maintenance issue of keeping filename and units aligned. If we decide to name the file with units (not recommended) then we should compute the name from the actual units in the file.

**Comment by lloyd-rmi** [comment]
The desire for this issue was to have the units tied to each column output within each file, rather than the file as a whole. Would request that we make that change so re-opening the issue. 

Agreed that avoiding hard coded units would be a less brittle approach as well.
